#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : opensm
Version  : 3.3.20
Release  : 11
URL      : https://www.openfabrics.org/downloads/management/opensm-3.3.20.tar.gz
Source0  : https://www.openfabrics.org/downloads/management/opensm-3.3.20.tar.gz
Summary  : InfiniBand subnet manager and administration
Group    : Development/Tools
License  : BSD-2-Clause GPL-2.0
Requires: opensm-bin = %{version}-%{release}
Requires: opensm-lib = %{version}-%{release}
Requires: opensm-license = %{version}-%{release}
Requires: opensm-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : flex
BuildRequires : rdma-core-dev

%description
OpenSM provides an implementation of an InfiniBand Subnet Manager and
Administration. Such a software entity is required to run for in order
to initialize the InfiniBand hardware (at least one per each
InfiniBand subnet).

%package bin
Summary: bin components for the opensm package.
Group: Binaries
Requires: opensm-license = %{version}-%{release}

%description bin
bin components for the opensm package.


%package dev
Summary: dev components for the opensm package.
Group: Development
Requires: opensm-lib = %{version}-%{release}
Requires: opensm-bin = %{version}-%{release}
Provides: opensm-devel = %{version}-%{release}
Requires: opensm = %{version}-%{release}

%description dev
dev components for the opensm package.


%package lib
Summary: lib components for the opensm package.
Group: Libraries
Requires: opensm-license = %{version}-%{release}

%description lib
lib components for the opensm package.


%package license
Summary: license components for the opensm package.
Group: Default

%description license
license components for the opensm package.


%package man
Summary: man components for the opensm package.
Group: Default

%description man
man components for the opensm package.


%prep
%setup -q -n opensm-3.3.20
cd %{_builddir}/opensm-3.3.20

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604353923
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604353923
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/opensm
cp %{_builddir}/opensm-3.3.20/COPYING %{buildroot}/usr/share/package-licenses/opensm/97bcb0df5ff699d85762a65622b272a1ac79c93c
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/opensm
/usr/bin/osmtest

%files dev
%defattr(-,root,root,-)
/usr/include/infiniband/complib/cl_atomic.h
/usr/include/infiniband/complib/cl_atomic_osd.h
/usr/include/infiniband/complib/cl_byteswap.h
/usr/include/infiniband/complib/cl_byteswap_osd.h
/usr/include/infiniband/complib/cl_comppool.h
/usr/include/infiniband/complib/cl_debug.h
/usr/include/infiniband/complib/cl_debug_osd.h
/usr/include/infiniband/complib/cl_dispatcher.h
/usr/include/infiniband/complib/cl_event.h
/usr/include/infiniband/complib/cl_event_osd.h
/usr/include/infiniband/complib/cl_event_wheel.h
/usr/include/infiniband/complib/cl_fleximap.h
/usr/include/infiniband/complib/cl_list.h
/usr/include/infiniband/complib/cl_log.h
/usr/include/infiniband/complib/cl_map.h
/usr/include/infiniband/complib/cl_math.h
/usr/include/infiniband/complib/cl_nodenamemap.h
/usr/include/infiniband/complib/cl_packoff.h
/usr/include/infiniband/complib/cl_packon.h
/usr/include/infiniband/complib/cl_passivelock.h
/usr/include/infiniband/complib/cl_pool.h
/usr/include/infiniband/complib/cl_ptr_vector.h
/usr/include/infiniband/complib/cl_qcomppool.h
/usr/include/infiniband/complib/cl_qlist.h
/usr/include/infiniband/complib/cl_qmap.h
/usr/include/infiniband/complib/cl_qpool.h
/usr/include/infiniband/complib/cl_spinlock.h
/usr/include/infiniband/complib/cl_spinlock_osd.h
/usr/include/infiniband/complib/cl_thread.h
/usr/include/infiniband/complib/cl_thread_osd.h
/usr/include/infiniband/complib/cl_threadpool.h
/usr/include/infiniband/complib/cl_timer.h
/usr/include/infiniband/complib/cl_timer_osd.h
/usr/include/infiniband/complib/cl_types.h
/usr/include/infiniband/complib/cl_types_osd.h
/usr/include/infiniband/complib/cl_vector.h
/usr/include/infiniband/iba/ib_cm_types.h
/usr/include/infiniband/iba/ib_types.h
/usr/include/infiniband/opensm/osm_attrib_req.h
/usr/include/infiniband/opensm/osm_base.h
/usr/include/infiniband/opensm/osm_config.h
/usr/include/infiniband/opensm/osm_congestion_control.h
/usr/include/infiniband/opensm/osm_console.h
/usr/include/infiniband/opensm/osm_console_io.h
/usr/include/infiniband/opensm/osm_db.h
/usr/include/infiniband/opensm/osm_db_pack.h
/usr/include/infiniband/opensm/osm_errors.h
/usr/include/infiniband/opensm/osm_event_plugin.h
/usr/include/infiniband/opensm/osm_file_ids.h
/usr/include/infiniband/opensm/osm_guid.h
/usr/include/infiniband/opensm/osm_helper.h
/usr/include/infiniband/opensm/osm_inform.h
/usr/include/infiniband/opensm/osm_lid_mgr.h
/usr/include/infiniband/opensm/osm_log.h
/usr/include/infiniband/opensm/osm_mad_pool.h
/usr/include/infiniband/opensm/osm_madw.h
/usr/include/infiniband/opensm/osm_mcast_mgr.h
/usr/include/infiniband/opensm/osm_mcast_tbl.h
/usr/include/infiniband/opensm/osm_mcm_port.h
/usr/include/infiniband/opensm/osm_mesh.h
/usr/include/infiniband/opensm/osm_msgdef.h
/usr/include/infiniband/opensm/osm_mtree.h
/usr/include/infiniband/opensm/osm_multicast.h
/usr/include/infiniband/opensm/osm_node.h
/usr/include/infiniband/opensm/osm_opensm.h
/usr/include/infiniband/opensm/osm_partition.h
/usr/include/infiniband/opensm/osm_path.h
/usr/include/infiniband/opensm/osm_perfmgr.h
/usr/include/infiniband/opensm/osm_perfmgr_db.h
/usr/include/infiniband/opensm/osm_pkey.h
/usr/include/infiniband/opensm/osm_port.h
/usr/include/infiniband/opensm/osm_port_profile.h
/usr/include/infiniband/opensm/osm_prefix_route.h
/usr/include/infiniband/opensm/osm_qos_policy.h
/usr/include/infiniband/opensm/osm_remote_sm.h
/usr/include/infiniband/opensm/osm_router.h
/usr/include/infiniband/opensm/osm_sa.h
/usr/include/infiniband/opensm/osm_sa_mad_ctrl.h
/usr/include/infiniband/opensm/osm_service.h
/usr/include/infiniband/opensm/osm_sm.h
/usr/include/infiniband/opensm/osm_sm_mad_ctrl.h
/usr/include/infiniband/opensm/osm_stats.h
/usr/include/infiniband/opensm/osm_subnet.h
/usr/include/infiniband/opensm/osm_switch.h
/usr/include/infiniband/opensm/osm_ucast_cache.h
/usr/include/infiniband/opensm/osm_ucast_lash.h
/usr/include/infiniband/opensm/osm_ucast_mgr.h
/usr/include/infiniband/opensm/osm_version.h
/usr/include/infiniband/opensm/osm_vl15intf.h
/usr/include/infiniband/opensm/st.h
/usr/include/infiniband/vendor/osm_vendor.h
/usr/include/infiniband/vendor/osm_vendor_api.h
/usr/include/infiniband/vendor/osm_vendor_ibumad.h
/usr/include/infiniband/vendor/osm_vendor_sa_api.h
/usr/lib64/libopensm.so
/usr/lib64/libosmcomp.so
/usr/lib64/libosmvendor.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libopensm.so.5
/usr/lib64/libopensm.so.5.2.3
/usr/lib64/libosmcomp.so.3
/usr/lib64/libosmcomp.so.3.0.10
/usr/lib64/libosmvendor.so.4
/usr/lib64/libosmvendor.so.4.0.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/opensm/97bcb0df5ff699d85762a65622b272a1ac79c93c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/torus-2QoS.conf.5
/usr/share/man/man8/opensm.8
/usr/share/man/man8/osmtest.8
/usr/share/man/man8/torus-2QoS.8
