#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : opensm
Version  : 3.3.20
Release  : 9
URL      : https://www.openfabrics.org/downloads/management/opensm-3.3.20.tar.gz
Source0  : https://www.openfabrics.org/downloads/management/opensm-3.3.20.tar.gz
Summary  : InfiniBand subnet manager and administration
Group    : Development/Tools
License  : BSD-2-Clause GPL-2.0
Requires: opensm-bin
Requires: opensm-lib
Requires: opensm-doc
BuildRequires : bison
BuildRequires : flex
BuildRequires : rdma-core-dev

%description
OpenSM provides an implementation of an InfiniBand Subnet Manager and
Administration. Such a software entity is required to run for in order
to initialize the InfiniBand hardware (at least one per each
InfiniBand subnet).

%package bin
Summary: bin components for the opensm package.
Group: Binaries

%description bin
bin components for the opensm package.


%package dev
Summary: dev components for the opensm package.
Group: Development
Requires: opensm-lib
Requires: opensm-bin
Provides: opensm-devel

%description dev
dev components for the opensm package.


%package doc
Summary: doc components for the opensm package.
Group: Documentation

%description doc
doc components for the opensm package.


%package lib
Summary: lib components for the opensm package.
Group: Libraries

%description lib
lib components for the opensm package.


%prep
%setup -q -n opensm-3.3.20

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1506718787
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1506718787
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/opensm
/usr/bin/osmtest

%files dev
%defattr(-,root,root,-)
/usr/include/infiniband/complib/cl_atomic.h
/usr/include/infiniband/complib/cl_atomic_osd.h
/usr/include/infiniband/complib/cl_byteswap.h
/usr/include/infiniband/complib/cl_byteswap_osd.h
/usr/include/infiniband/complib/cl_comppool.h
/usr/include/infiniband/complib/cl_debug.h
/usr/include/infiniband/complib/cl_debug_osd.h
/usr/include/infiniband/complib/cl_dispatcher.h
/usr/include/infiniband/complib/cl_event.h
/usr/include/infiniband/complib/cl_event_osd.h
/usr/include/infiniband/complib/cl_event_wheel.h
/usr/include/infiniband/complib/cl_fleximap.h
/usr/include/infiniband/complib/cl_list.h
/usr/include/infiniband/complib/cl_log.h
/usr/include/infiniband/complib/cl_map.h
/usr/include/infiniband/complib/cl_math.h
/usr/include/infiniband/complib/cl_nodenamemap.h
/usr/include/infiniband/complib/cl_packoff.h
/usr/include/infiniband/complib/cl_packon.h
/usr/include/infiniband/complib/cl_passivelock.h
/usr/include/infiniband/complib/cl_pool.h
/usr/include/infiniband/complib/cl_ptr_vector.h
/usr/include/infiniband/complib/cl_qcomppool.h
/usr/include/infiniband/complib/cl_qlist.h
/usr/include/infiniband/complib/cl_qmap.h
/usr/include/infiniband/complib/cl_qpool.h
/usr/include/infiniband/complib/cl_spinlock.h
/usr/include/infiniband/complib/cl_spinlock_osd.h
/usr/include/infiniband/complib/cl_thread.h
/usr/include/infiniband/complib/cl_thread_osd.h
/usr/include/infiniband/complib/cl_threadpool.h
/usr/include/infiniband/complib/cl_timer.h
/usr/include/infiniband/complib/cl_timer_osd.h
/usr/include/infiniband/complib/cl_types.h
/usr/include/infiniband/complib/cl_types_osd.h
/usr/include/infiniband/complib/cl_vector.h
/usr/include/infiniband/iba/ib_cm_types.h
/usr/include/infiniband/iba/ib_types.h
/usr/include/infiniband/opensm/osm_attrib_req.h
/usr/include/infiniband/opensm/osm_base.h
/usr/include/infiniband/opensm/osm_config.h
/usr/include/infiniband/opensm/osm_congestion_control.h
/usr/include/infiniband/opensm/osm_console.h
/usr/include/infiniband/opensm/osm_console_io.h
/usr/include/infiniband/opensm/osm_db.h
/usr/include/infiniband/opensm/osm_db_pack.h
/usr/include/infiniband/opensm/osm_errors.h
/usr/include/infiniband/opensm/osm_event_plugin.h
/usr/include/infiniband/opensm/osm_file_ids.h
/usr/include/infiniband/opensm/osm_guid.h
/usr/include/infiniband/opensm/osm_helper.h
/usr/include/infiniband/opensm/osm_inform.h
/usr/include/infiniband/opensm/osm_lid_mgr.h
/usr/include/infiniband/opensm/osm_log.h
/usr/include/infiniband/opensm/osm_mad_pool.h
/usr/include/infiniband/opensm/osm_madw.h
/usr/include/infiniband/opensm/osm_mcast_mgr.h
/usr/include/infiniband/opensm/osm_mcast_tbl.h
/usr/include/infiniband/opensm/osm_mcm_port.h
/usr/include/infiniband/opensm/osm_mesh.h
/usr/include/infiniband/opensm/osm_msgdef.h
/usr/include/infiniband/opensm/osm_mtree.h
/usr/include/infiniband/opensm/osm_multicast.h
/usr/include/infiniband/opensm/osm_node.h
/usr/include/infiniband/opensm/osm_opensm.h
/usr/include/infiniband/opensm/osm_partition.h
/usr/include/infiniband/opensm/osm_path.h
/usr/include/infiniband/opensm/osm_perfmgr.h
/usr/include/infiniband/opensm/osm_perfmgr_db.h
/usr/include/infiniband/opensm/osm_pkey.h
/usr/include/infiniband/opensm/osm_port.h
/usr/include/infiniband/opensm/osm_port_profile.h
/usr/include/infiniband/opensm/osm_prefix_route.h
/usr/include/infiniband/opensm/osm_qos_policy.h
/usr/include/infiniband/opensm/osm_remote_sm.h
/usr/include/infiniband/opensm/osm_router.h
/usr/include/infiniband/opensm/osm_sa.h
/usr/include/infiniband/opensm/osm_sa_mad_ctrl.h
/usr/include/infiniband/opensm/osm_service.h
/usr/include/infiniband/opensm/osm_sm.h
/usr/include/infiniband/opensm/osm_sm_mad_ctrl.h
/usr/include/infiniband/opensm/osm_stats.h
/usr/include/infiniband/opensm/osm_subnet.h
/usr/include/infiniband/opensm/osm_switch.h
/usr/include/infiniband/opensm/osm_ucast_cache.h
/usr/include/infiniband/opensm/osm_ucast_lash.h
/usr/include/infiniband/opensm/osm_ucast_mgr.h
/usr/include/infiniband/opensm/osm_version.h
/usr/include/infiniband/opensm/osm_vl15intf.h
/usr/include/infiniband/opensm/st.h
/usr/include/infiniband/vendor/osm_vendor.h
/usr/include/infiniband/vendor/osm_vendor_api.h
/usr/include/infiniband/vendor/osm_vendor_ibumad.h
/usr/include/infiniband/vendor/osm_vendor_sa_api.h
/usr/lib64/libopensm.so
/usr/lib64/libosmcomp.so
/usr/lib64/libosmvendor.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man5/*
%doc /usr/share/man/man8/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libopensm.so.5
/usr/lib64/libopensm.so.5.2.3
/usr/lib64/libosmcomp.so.3
/usr/lib64/libosmcomp.so.3.0.10
/usr/lib64/libosmvendor.so.4
/usr/lib64/libosmvendor.so.4.0.2
